# Generated by Django 2.1.7 on 2019-03-31 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planargraph',
            fields=[
                ('planargraphId', models.AutoField(primary_key=True, serialize=False, verbose_name='平面圖id')),
                ('name', models.CharField(max_length=20, verbose_name='名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('spaceId', models.AutoField(primary_key=True, serialize=False, verbose_name='空間id')),
                ('name', models.CharField(max_length=20, verbose_name='名稱')),
                ('x', models.CharField(max_length=20)),
                ('y', models.CharField(max_length=20)),
                ('w', models.CharField(max_length=20)),
                ('h', models.CharField(max_length=20)),
                ('planargraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planargraphs.Planargraph')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='信箱')),
                ('password', models.CharField(max_length=20, verbose_name='密碼')),
                ('username', models.CharField(max_length=20, verbose_name='使用者名稱')),
            ],
        ),
        migrations.AddField(
            model_name='planargraph',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planargraphs.Users'),
        ),
    ]
