# Generated by Django 2.1.7 on 2019-04-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planargraphs', '0003_auto_20190331_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='h',
        ),
        migrations.RemoveField(
            model_name='space',
            name='w',
        ),
        migrations.RemoveField(
            model_name='space',
            name='x',
        ),
        migrations.RemoveField(
            model_name='space',
            name='y',
        ),
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(default=None, upload_to='static/images/', verbose_name='圖片'),
        ),
    ]
