# Generated by Django 2.1.7 on 2019-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planargraphs', '0004_auto_20190402_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
