# Generated by Django 2.1.7 on 2019-04-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planargraphs', '0005_auto_20190402_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.URLField(default='https://image.flaticon.com/icons/svg/25/25235.svg', verbose_name='圖片'),
        ),
    ]
