# Generated by Django 2.1.7 on 2019-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planargraphs', '0006_auto_20190403_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.URLField(verbose_name='圖片'),
        ),
    ]
