# Generated by Django 2.1.7 on 2019-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planargraphs', '0007_auto_20190405_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.CharField(max_length=100, verbose_name='圖片'),
        ),
    ]
