# Generated by Django 2.1.7 on 2019-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planargraphs', '0008_auto_20190406_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.CharField(max_length=200, verbose_name='圖片'),
        ),
    ]
