# Generated by Django 2.1.7 on 2019-04-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planargraphs', '0009_auto_20190407_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.CharField(choices=[('square.png', '正方形'), ('rectangle.png', '長方形')], max_length=200, verbose_name='圖片'),
        ),
    ]
