# Generated by Django 2.1.7 on 2019-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planargraphs', '0010_auto_20190408_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.CharField(choices=[('square.png', '正方形'), ('rectangle.png', '長方形'), ('rectangle-2.png', 'L形'), ('triangle.png', '三角形')], max_length=200, verbose_name='圖片'),
        ),
    ]
